"""add_port_observability_columns

Revision ID: b381f2acc5c6
Revises: 
Create Date: 2026-07-23 15:08:51.356560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b381f2acc5c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carrier_search_results', sa.Column('raw_origin_input', sa.String(length=255), nullable=True))
    op.add_column('carrier_search_results', sa.Column('raw_destination_input', sa.String(length=255), nullable=True))
    op.add_column('carrier_search_results', sa.Column('resolved_origin_name', sa.String(length=255), nullable=True))
    op.add_column('carrier_search_results', sa.Column('resolved_origin_locode', sa.String(length=50), nullable=True))
    op.add_column('carrier_search_results', sa.Column('resolved_destination_name', sa.String(length=255), nullable=True))
    op.add_column('carrier_search_results', sa.Column('resolved_destination_locode', sa.String(length=50), nullable=True))
    op.add_column('carrier_search_results', sa.Column('submitted_origin', sa.String(length=255), nullable=True))
    op.add_column('carrier_search_results', sa.Column('submitted_destination', sa.String(length=255), nullable=True))
    op.add_column('carrier_search_results', sa.Column('matched_origin', sa.String(length=255), nullable=True))
    op.add_column('carrier_search_results', sa.Column('matched_destination', sa.String(length=255), nullable=True))
    op.add_column('carrier_search_results', sa.Column('has_port_mismatch', sa.Boolean(), nullable=True))
    op.add_column('carrier_search_results', sa.Column('mismatch_warning', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carrier_search_results', 'mismatch_warning')
    op.drop_column('carrier_search_results', 'has_port_mismatch')
    op.drop_column('carrier_search_results', 'matched_destination')
    op.drop_column('carrier_search_results', 'matched_origin')
    op.drop_column('carrier_search_results', 'submitted_destination')
    op.drop_column('carrier_search_results', 'submitted_origin')
    op.drop_column('carrier_search_results', 'resolved_destination_locode')
    op.drop_column('carrier_search_results', 'resolved_destination_name')
    op.drop_column('carrier_search_results', 'resolved_origin_locode')
    op.drop_column('carrier_search_results', 'resolved_origin_name')
    op.drop_column('carrier_search_results', 'raw_destination_input')
    op.drop_column('carrier_search_results', 'raw_origin_input')
    # ### end Alembic commands ###
