raw_text = """
GDYNIA	USD				
GDANSK	USD				
ANTWERP	USD				
BARCELONA	USD				
BURGAS	USD				
PIRAEUS	USD				
FELIXSTOWE	USD				
LEIXOES	USD				
ROTTERDAM	USD				
HAMBURG	USD				
SOKHNA	USD				
KARACHI	USD				
NEW YORK	USD				
KOPER	USD				
LIVERPOOL	USD				
BRISTOL	USD				
HOUSTON	USD				
CHITTAGONG	USD				
THESSALONIKI	USD				
BUENOS AIRES	USD				
MOJI	USD				
VALENCIA	USD				
TIHI	USD				
KAMALAPUR/DHAKA	USD				
SAVANNAH	USD				
OSAKA	USD				
ANTWERP	USD				
AHMEDABAD	USD				
PORT SAID WEST	USD				
NIIGATA	USD				
BUSAN	USD				
SANTOS BRAZIL	USD				
BANGALORE	USD				
CEBU	USD				
SAVANNAH GEORGIA	USD				
CORK PORT, IRELAND	USD				
YOKOHAMA	USD				
KOBE	USD				
NAGOYA	USD				
MUNDRA	USD				
CHITTAGONG	USD				
ISTANBUL	USD				
JAKARTA	USD				
BELAWAN	USD				
HAIPHONG	USD				
MERSIN	USD				
AMBARLI	USD				
INCHEON	USD				
COLOMBO	USD				
CHENNAI	USD				
JEBEL ALI	USD				
SURABAYA	USD				
BANGKOK	USD				
LAEM CHABANG	USD				
CAT LAI	USD				
DAMMAM	USD				
CHIBA	USD				
CHATTOGRAM	USD				
KAOHSIUNG	USD				
KLAIPEDA	USD				
VENICE	USD				
SALERNO	USD				
RAVENNA	USD				
LA SPEZIA	USD				
CONSTANTA	USD				
FREMANTLE	USD				
VANCOUVER	USD				
TORONTO (HALIFAX)	USD				
TORONTO (VANCOUVER)	USD				
MONTREAL (HALIFAX)	USD				
MONTREAL (VANCOUVER)	USD				
MONTREAL (ALL WATER SERVICE)	USD				
WINNIPEG	USD				
BALTIMORE	USD				
PYEONGTAEK	USD				
LONG BEACH	USD				
IZMIT	USD				
KUMPORT	USD				
ALEXANDRIA	USD				
BRISBANE	USD				
MELBOURNE	USD				
AUCKLAND	USD				
TAURANGA	USD				
YOKOHAMA	USD				
LOS ANGELES	USD				
PHILADELPHIA	USD				
MONTEVIDEO	USD				
TANJUNG PRIOK (JAKARTA)	USD				
NAGOYA	USD				
YOKOHAMA	USD				
MANZANILLO	USD				
MALAGA	USD				
KOLKATA	USD				
GEBZE	USD				
DILIKELESI	USD				
BILBAO	USD				
BUENAVENTURA	USD				
BUENOS AIRES	USD				
HAMAD	USD				
CAMDEN	USD				
COPENHAGEN	USD				
CHICAGO	USD				
MILWAUKEE	USD				
PARANAGUA	USD				
ALTAMIRA	USD				
LOME	USD				
BUDAPEST	USD				
HELSINKI	USD				
TOKYO	USD				
DOHA	USD				
NAVEGANTES	USD				
ITAPOA	USD				
MALAGA	USD				
FUNABASHI	USD				
ROSARIO	USD				
BOURGES	USD				
SIHANOUKVILLE	USD				
DILISKELESI	USD				
PIPAVAV	USD				
KATTUPALLI	USD				
VISAKHAPATNAM	USD				
HALDIA	USD				
DHAKA & KAMLAPUR	USD				
JEDDAH	USD				
AL-SOKHNA	USD				
AQABA	USD				
DJIBOUTI	USD				
DAMIETTA	USD				
IZMIR	USD				
LAT KRABANG	USD
MANILA	USD
NHAVA SHEVA	USD
BOSTON	USD
CEBU	USD
CHARLESTON	USD
NORFOLK	USD
JACKSONVILLE	USD
OAKLAND	USD
MIAMI (ALL WATER)	USD
EDMONTON (VANCOUVER)	USD
SAKASTOON	USD
YANGON	USD
"""

clean_ports = []
for line in raw_text.strip().split('\n'):
    cleaned = line.replace('\tUSD', '').replace('USD', '').strip()
    if cleaned:
        clean_ports.append(cleaned)

print(f"Total destination ports extracted: {len(clean_ports)}")
print("\nFormatted RFQ Text Below:")
print("-" * 50)
print("Hi Team,\nPlease compile ocean freight rates from ex Pasir Gudang for 20'GP and 40'GP containers (weight 25,000 kg per container).\nCarriers: Maersk, Hapag-Lloyd.\n")
for i, port in enumerate(clean_ports, 1):
    print(f"{i}) {port}")
